services:
  - type: web
    name: capstone-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Backend/capstone-service/Dockerfile
    dockerContext: ./Backend/capstone-service
    envVars:
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/products
